Add event script
ISISComputingGroup/EPICS-inst_servers pull request #196
Opened 2019-04-04 09:12 UTC by John-Holt-Tessella

Get all events from Database

2021-02-15 12:23 UTC, DominicOram commented on scripts/log_event_generator.py
> +        exit(1)
nit: Pull this into a function

2021-02-15 20:28 UTC, DominicOram requested changes
Works well, thanks. Only major issue is that the date seems to be formatted wrong. You can see it in the example in the documentation where you have a date of `2021-33-29 15:01:53`. Comments in code are minor, especially given it's just a developer tool, feel free to do as much as you like with it.

2021-02-15 20:28 UTC, DominicOram commented on scripts/restore_motor_positions.py
> +    print_and_log(f'{"name":12} {"motor":7}: {"db value":12} {"diff from":12} - {"last update":19} '
nit: As elsewhere i feel like `historic` is better than `db`

2021-02-15 20:58 UTC, DominicOram commented on scripts/restore_motor_positions.py
> +                  "--prefix IN:IMAT:MOT --controller 01"
You don't need to specify the MOT in the prefix

2021-02-15 21:00 UTC, DominicOram commented
Also, could one of the prefix/host default to the other if only one specified. e.g. if you specify `--host IMAT` then the prefix should default to `IN:IMAT` and vis-versa. It would make the interface nicer and it's unlikely you would want to read from one instrument and set to another.

2021-02-16 11:19 UTC, John-Holt-Tessella commented on scripts/log_event_generator.py
> +        exit(1)
good plan, done

2021-02-16 11:59 UTC, John-Holt-Tessella commented on scripts/restore_motor_positions.py
> +        check_movement_for: time to check for motor movement
this is in the signature, which is more accurate than the comment

2021-02-16 12:02 UTC, John-Holt-Tessella commented
> Also, could one of the prefix/host default to the other if only one specified. e.g. if you specify `--host IMAT` then the prefix should default to `IN:IMAT` and vis-versa. It would make the interface nicer and it's unlikely you would want to read from one instrument and set to another. (but still allow it by specifying both)

Yeah but this requires interrogating the inst list and in 99% of cases the user does not specify either since you can only restore motor positions on the instrument.

2021-02-16 12:07 UTC, John-Holt-Tessella commented on scripts/restore_motor_positions.py
> +        prefix = args.prefix
has to be done after set instrument which needs to be done after host is known

2021-02-16 15:55 UTC, DominicOram approved these changes
Great, thank you

2021-02-16 15:55 UTC, merged