Ticket4882: Convert blockserver to python 3
ISISComputingGroup/EPICS-inst_servers pull request #324
Opened 2020-11-17 16:11 UTC by rerpha

### Description of work

*Add your own description here*

### To test

*Which ticket does this PR fix?*

### Acceptance criteria

*List the acceptance criteria for the PR*

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Has the author taken into account the multi-threaded nature of the code?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated?

### Functional Tests

- [ ] Do changes function as described? Add comments below that describe the tests performed.

### Final steps

- [ ] Reviewer has updated the submodule in the main EPICS repo? See **Reviewing work for the subModules of EPICS** in the [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

2020-12-03 14:34 UTC, Tom-Willemsen requested changes
Mostly good, thanks. I was able to do the typical blockserver operations successfully with py3.

A few comments in the code. Also, on blockserver startup, I am getting:

```
[1607003689.31] MAJOR: Could not retrieve IOC list: Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\database_client.py", line 23, in get_iocs
    rawjson = dehex_and_decompress(bytes(ChannelAccess.caget(prefix + DatabasePVNames.IOCS), encoding="utf-8")).decode("utf-8")
TypeError: encoding without a string argument
```

2020-12-04 14:58 UTC, rerpha commented
> Mostly good, thanks. I was able to do the typical blockserver operations successfully with py3.
> 
> A few comments in the code. Also, on blockserver startup, I am getting:
> 
> ```
> [1607003689.31] MAJOR: Could not retrieve IOC list: Traceback (most recent call last):
>   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\database_client.py", line 23, in get_iocs
>     rawjson = dehex_and_decompress(bytes(ChannelAccess.caget(prefix + DatabasePVNames.IOCS), encoding="utf-8")).decode("utf-8")
> TypeError: encoding without a string argument
> ```

this is really weird, i get the error as well but if you remove the bytes() cast in theory it should work but instead raises this exception: 

```
[Fri Dec  4 14:54:30 2020] [1607093670.12] MAJOR: Could not retrieve IOC list: Traceback (most recent call last):

[Fri Dec  4 14:54:30 2020]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\BlockServer\core\database_client.py", line 23, in get_iocs

[Fri Dec  4 14:54:30 2020]     rawjson = dehex_and_decompress(ChannelAccess.caget(prefix + DatabasePVNames.IOCS)).decode("utf-8")

[Fri Dec  4 14:54:30 2020]   File "C:\Instrument\Apps\EPICS\ISIS\inst_servers\master\server_common\utilities.py", line 108, in dehex_and_decompress

[Fri Dec  4 14:54:30 2020]     assert type(value) == bytes, \

[Fri Dec  4 14:54:30 2020] AssertionError: Non-bytes argument passed to dehex_and_decompress, maybe Python 2/3 compatibility issue

[Fri Dec  4 14:54:30 2020] Argument was type NoneType with value None
```

which suggests to me that somewhere it is read as string and somewhere else as bytes... I think this error is why i used the `value if bytes else bytes(value)` cast elsewhere

2020-12-04 15:01 UTC, Tom-Willemsen commented
> `Argument was type NoneType with value None`

This is the issue... looks like it is trying to hex and compress `None`. You need to find where that is coming from, `None` should never be a valid type to pass to `dehex_and_decompress`.

2020-12-04 15:03 UTC, rerpha commented on BlockServer/test_modules/test_configuration_json.py
> +# TODO: add tests here for blocks & IOCs
I think this can be removed, the groups don't handle proper ioc objects anyway and those are tested when converting to XML

2020-12-04 15:09 UTC, rerpha commented
It looks like it's coming from the caget itself which gives back None if it doesn't read a value - should i suppress it or do you think this is a valid error?

2020-12-08 19:18 UTC, Tom-Willemsen approved these changes

2020-12-08 19:18 UTC, merged